M48
; DRILL file {KiCad 7.0.10} date lun 29 gen 2024, 12:38:07
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-29T12:38:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.65Y-3.5
X5.85Y-3.2
T2
X5.05Y-3.0
X5.05Y-3.7
M30
